### ISSUE TITLE
Problem with latin symbols in subject of the e-mail

### ISSUE THREAD

**Issue by KarelSalay** [WPManageNinja/fluent-smtp#1]
Hello,
I have problem with latin symbols in subject of the e-mail.

Could you please help me with this issue?
![image](https://user-images.githubusercontent.com/61360333/105068949-b8a47a00-5a81-11eb-842f-4f433e13c163.png)

Thank you
Karel

karel@salay.cz

**Comment by KarelSalay** [comment]
Today I tested more, and it is not only in subject name in e-mail:

[HledÃ¡m karavan] Post Expiration Complete "Yamaha XV1900 Stratoliner"
Yamaha XV1900 Stratoliner (https://hledamkaravan.cz/…er/) expiroval dnes v 20. 1. 2021 14:42. Stav inzerÃ¡tu byl ÃºspÄÅ¡nÄ zmÄnÄn na "DRAFT".

**Comment by techjewel** [comment]
Can you give me some subject lines that I can test locally?

**Comment by KarelSalay** [comment]
Text from subject line: VytvoÅ™enÃ­ novÃ©ho inzerÃ¡tu

**Comment by KarelSalay** [comment]
Hello, any news please? 
Thank you
Karel

**Comment by matute2999** [comment]
I am having the same issue. All the accents like á é etc get replaced by weird symbols!

**Comment by techjewel** [comment]
Fixed in latest version 1.0.1
