### ISSUE TITLE
Issue setting connection with Office 365 using modern authentication

### ISSUE THREAD

**Issue by jmartin-pukkas** [WPManageNinja/fluent-smtp#127]
Hello there,

We have an issue regarding a connection with Office365. The details are:

When we click the the Get Access Token red button to get the token, it works, we take it and put it on the auth token text field, we save it and it works nicely.

Then, when we go to Check connection validty (pressing the eye button of the connection) it tell us:

Token Validity: Invalid. Please re-authenticate

We have tested it with all the standard browsers disabling security plugin, and we are using latest Wordpress and FluentSMTP plugin version.

Thanks and regards

**Comment by techjewel** [comment]
Please with latest version of FluentSMTP
