### ISSUE TITLE
[Feature Request] Getting more information in the log

### ISSUE THREAD

**Issue by ManniGH** [WPManageNinja/fluent-smtp#133]
Would it be possible to see in the log if the email was opened? When sending system emails (either wordpress ones or when we import users using Uncanny Owl import tool for Learndash), we need to know which user receive our emails / open them.
This is possible in other plugins (as well as seeing if a link was clicked), it would be great if this could be added to fluentSMTP, as we've purchased most of the Fluent products and it would be nice to have the stmp plugin integrated, for better compatibility.
Of course this is handled by FluentCRM when sending campaigns, but this is needed when the sender is NOT FluentCRM.
Thank you for considering this feature request!

**Comment by techjewel** [comment]
We don't have any plan for this feature into FluentSMTP
