### ISSUE TITLE
Problem sending Email notifications to Microsoft 365 server emails

### ISSUE THREAD

**Issue by mast01** [WPManageNinja/fluent-smtp#134]
Hello, I have a page where I’m using Fluent Forms, I’ve install Fluent SMTP plugin and everything is going perfectly. I only have a problem, but it is getting a big problem for us, the email notification are beening sends to every mail for the users without problem, but the mails from our admin server (@arivogroup.com the server is a microsoft 365 contract) are failing to be sent, I have tried to send every account that with get into that domain and every time it get failed.

I have not been able to check in others Microsoft 365 domain emails, so not sure if there is a problem with fluent SMTP and microsoft 365, or if there is a problem with the domain emails.

Please is someone know what could be happening, I will be glad to read some ideas.
![FLUENT SMTP ERROR](https://user-images.githubusercontent.com/53539134/196832054-c8e7828b-01a1-4469-9540-e43b2a007900.jpg)

**Comment by sadrian80** [comment]
We are seeing this issue too in two WP instances. Both work normal, yet on some occasions, we get the same error as @mast01. Resetting the authentication does not solve the issue.

**Comment by sadrian80** [comment]
This could be related to issues #130 and #92:
With attachments bigger than 3MB, the file data must be transmitted via PUT (instead of POST) as per documentation:
https://learn.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http

I guess this has to be implemented on your site @techjewel ?

**Comment by mast01** [comment]
In my case the email notifications had no attachments. They were HTML emails with just text and styling.
