### ISSUE TITLE
Office Connection - Application asked for scope that does not exist on resource

### ISSUE THREAD

**Issue by JanickLehmann** [WPManageNinja/fluent-smtp#154]
I was unable to setup the Office 365 connection to send emails using the API.
Authenticating to get the access token resulted in the error (which was sadly only visible in the URL query string):
> AADSTS650053: The application '{name}' asked for scope '{scope}' that doesn't exist on the resource '{resource}'. Contact the app vendor.

In my case:
- {name} is irrelevant (but matched Azure AD)
- {scope} was `user.read%0a`
- {resource} was `00000003-0000-0000-c000-000000000000` (which I think is the GUID for MS Graph, but doesn't matter in this case)

I noticed the `%0a` (url encoded line feed) at the end of the scope name.
Resolving this myself involved editing `API.php` to remove the line breaks between the scopes.
The new `getConfig()` function now looks like this:
```php
private function getConfig()
{
    return [
        'clientId'                => $this->clientId,
        'clientSecret'            => $this->clientSecret,
        'redirectUri'             => $this->getRedirectUrl(),
        'urlAuthorize'            => 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
        'urlAccessToken'          => 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
        'urlResourceOwnerDetails' => '',
        'scopes'                  => 'https://graph.microsoft.com/user.read https://graph.microsoft.com/mail.readwrite https://graph.microsoft.com/mail.send https://graph.microsoft.com/mail.send.shared offline_access'
    ];
}
```

After my edit, the setup worked fine.
I suggest adding this fix in the next update that other users setting up their O365 connection do not run into the same problem.

**Comment by techjewel** [comment]
Thank you so much for providing the fix. I just released the update (version 2.2.4)
🙌
