### ISSUE TITLE
Suddenly for no reason from my end PW of email got corrupted and no SMTP worked

### ISSUE THREAD

**Issue by curlygirly1** [WPManageNinja/fluent-smtp#185]
Hi. Today on one of my sites no WP emails reached me. I also use 2FA plugin so was a hassle to login.
I use Hostinger for my sites' SMTP emails.
After finally logging in, I checked your plugin settings for the email. 
And I saw the PW was unusually short so I re-inputted it and then all worked again.

Why this issue? Have you pushed an update recently?

**Comment by techjewel** [comment]
We did not push any update recently.
