### ISSUE TITLE
Using SparkPost to send emails, but getting a "Generation Failure" error. Can't send the email successfully.

### ISSUE THREAD

**Issue by RichardDBrown** [WPManageNinja/fluent-smtp#221]
All the from email fields are empty.

![image](https://github.com/user-attachments/assets/973f7964-bc7b-4e95-8a83-a50464057811)

![image](https://github.com/user-attachments/assets/b810c290-83f0-40a8-8fb1-b6873a75e39a)

**Comment by JtwoA** [comment]
I'm seeing the same with SparkPost.

**Comment by RichardDBrown** [comment]
If you encounter the issues mentioned above, don't choose SparkPost. You can select "other SMTP settings," enter the relevant information, and it should work too.

**Comment by DavePodosyan** [comment]
Seeing the same issue with SparkPost using API key
