### ISSUE TITLE
Wordpress 5.7.1 breaks FluentSMTP

### ISSUE THREAD

**Issue by morayf** [WPManageNinja/fluent-smtp#25]
Having applied the latest wordpress 5.7.1 update, the FluentSMTP plugin breaks with a simple "Error" message on form submissions.  The emails actually get sent, but forms display the error and no log is created.  Deactivating the plugin, forms submit with the success msg.

**Comment by techjewel** [comment]
We have fixed the issue on version 1.1.1
Please update to latest version.
