### ISSUE TITLE
Problem with some characters getting replaced with weird symbols

### ISSUE THREAD

**Issue by matute2999** [WPManageNinja/fluent-smtp#3]
All the special characters, like accents, get replaced by weird symbols.

<img width="660" alt="Screen Shot 2021-01-22 at 12 50 20 PM" src="https://user-images.githubusercontent.com/77848244/105512883-6f863d00-5cb0-11eb-8d14-c5eee8064a7d.png">

**Comment by techjewel** [comment]
We are working on this. We will release an update soon.

**Comment by techjewel** [comment]
Fixed in latest version 1.0.1
