### ISSUE TITLE
No email log

### ISSUE THREAD

**Issue by TheZoker** [WPManageNinja/fluent-smtp#43]
The email log page does not show me any emails:
![image](https://user-images.githubusercontent.com/1368405/126903975-8723b5e8-ccc5-4187-89b0-1c3a0bc1b7da.png)

Although there are entries in the database:
![image](https://user-images.githubusercontent.com/1368405/126904063-6df44145-3740-41f9-a60a-c6ce2fcc6940.png)

Is this a bug?

**Comment by techjewel** [comment]
Hello @TheZoker 
Thanks for reporting the issue. Not sure what went wrong but that's not ideal. Can you send me an email @ cep.jewel[at]gmail[dot]com

Would love to debug the issue with you and find a resulation.

**Comment by techjewel** [comment]
Fixed at 2.0.0
