### ISSUE TITLE
Recommended plugin installation bypasses DISALLOW_FILE_MODS setting

### ISSUE THREAD

**Issue by tombonez** [WPManageNinja/fluent-smtp#44]
Hi 👋

The Recommended Plugin section on the Support page bypasses the wp-config.php [DISALLOW_FILE_MODS](https://wordpress.org/support/article/editing-wp-config-php/#disable-plugin-and-theme-update-and-installation) constant.

To fix this, the below code could be added to **app/Hooks/Handlers/filters.php** or similar to prevent the recommendations list from showing:

```php
if(defined('DISALLOW_FILE_MODS') && DISALLOW_FILE_MODS) {
    add_filter('fluentmail_disable_recommendation', '__return_true');
}
```

Along with updating the **installPlugin** function found in **app/Http/Controllers/SettingsController.php** to prevent this behaviour from ever being able to run. For example:

```php
if(!isset($UrlMaps[$pluginSlug]) || (defined('DISALLOW_FILE_MODS') && DISALLOW_FILE_MODS)) {
    $this->sendError([
        'message' => __('Sorry, You can not install this plugin', 'fluent-smtp')
    ]);
}
```

Happy to submit a Pull Request if the above works for you.

Cheers,
Tom 🙂

**Comment by techjewel** [comment]
Please feel free to submit a pull request

**Comment by tombonez** [comment]
@techjewel Awesome! I'll get that sorted this evening 🙂
