### ISSUE TITLE
Amazon SES connection deleted while adding Sendgrid connection

### ISSUE THREAD

**Issue by EngageNow** [WPManageNinja/fluent-smtp#53]
I used Amazon SES for the last few weeks. Today I wanted to add a secondary connection, Sendgrid. Once the connection was added successfully, I found that thee Amazon SES connection was deleted. I am 100% sure I didn't delete it. Could this be an issue?

**Comment by EngageNow** [comment]
Just add Amazon SES again, and Sendgrid connection was deleted. So it seems that only 1 connection can be added, adding a new one will delete the existing one.

**Comment by Jahsun3777** [comment]
Same issue here. You can only add one.

**Comment by techjewel** [comment]
Please make sure your form email address is different. FluentSMTP use from email address to map the connections.
