### ISSUE TITLE
Amazon SES - Save Connection Settings gets stuck on "Validating Data. Please wait"

### ISSUE THREAD

**Issue by chrishthompson** [WPManageNinja/fluent-smtp#60]
Problem:
- Can't add new Amazon SES connections
- Can't change existing Amazon SES connections in any way.

Observations:
- I have several sites using FluentSMTP with working Amazon SES connections. 
- All of these sites can still send via the SES connections so the credentials are still fine.  (And I can see the credentials are still working in AWS IAM)
- I can add other connection providers with no problem...but I haven't tried them all.
- I can delete Amazon SES connections with no problem...but I can't add them back unless I recover from a backup.
- Impacting sites running on different servers with different sets of plugins and themes.
- All sites are running WP 5.8.1 and FluentSMTP 2.0.1

I'm investigating further.

**Comment by chrishthompson** [comment]
More info:
- I haven't been able to resolve the SES connection issue by deactivating other plugins.
- I installed WP Offload SES Lite and was able to connect with the same credentials (with keys in DB and then in wp-config)
- I did not test FluentSMTP with SES credential keys in wp-config, so I can't say whether that has the same issue.

I'm still running FluentSMTP on most of my sites and still using SES on those sites without issue.  For new sites, or for any email changes, I will have to use WP Offload SES until this is resolved.  I hope this helps, and thanks for making an awesome plugin!  👍

**Comment by sbtre** [comment]
SAME HERE!

<img width="1577" alt="Screenshot 2021-09-28 154057" src="https://user-images.githubusercontent.com/39118610/135098336-325df7fa-5cff-494a-ae78-92573fa7f3df.png">

**Comment by chrishthompson** [comment]
Issue is resolved as of version 2.1.0.  I'm going to close it.  My guess (without verification) is that it may have been related to the PHP 8 issue that they resolved in this version.  All of my effected sites were running PHP 8...

@sbtre FYI - maybe your issue is fixed?
